add Flask build support for Android dev builds

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1320,7 +1320,14 @@ workflows:
                 if [ -n "$YARN_COMMAND" ]; then
                     GIT_BRANCH=$BITRISE_GIT_BRANCH yarn "$YARN_COMMAND"
                 elif [ "$IS_DEV_BUILD" = "true" ]; then #EXPO BUILD
-                    GIT_BRANCH=$BITRISE_GIT_BRANCH yarn build:android:devbuild
+                    if [ "$METAMASK_BUILD_TYPE" = "main" ]; then
+                        GIT_BRANCH=$BITRISE_GIT_BRANCH yarn build:android:devbuild
+                    elif [ "$METAMASK_BUILD_TYPE" = "flask" ]; then
+                        GIT_BRANCH=$BITRISE_GIT_BRANCH yarn build:android:devbuild:flask
+                    else
+                        echo "Error: Invalid build type specified: $METAMASK_BUILD_TYPE"
+                        exit 1
+                    fi
                 elif [ "$METAMASK_BUILD_TYPE" = "main" ]; then
                     yarn build:android:pre-release:bundle
                 elif [ "$METAMASK_BUILD_TYPE" = "beta" ]; then
@@ -1337,6 +1344,8 @@ workflows:
           inputs:
             - content: |-
                 #!/usr/bin/env bash
+                set -ex
+
                 # Set base paths for release builds
                            if [ "$IS_DEV_BUILD" = "true" ]; then
                     APK_DIR="$PROJECT_LOCATION/app/build/outputs/apk/$APP_NAME/debug"
