added release template and beta android builds

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1175,7 +1175,7 @@ workflows:
           inputs:
             - abort_on_fail: 'yes'
             - access_token: $BITRISE_START_BUILD_ACCESS_TOKEN
-  build_android_release:
+  _android_build_template:
     before_run:
       - code_setup
     after_run:
@@ -1200,7 +1200,17 @@ workflows:
             - content: |-
                 #!/usr/bin/env bash
                 node -v
-                METAMASK_BUILD_TYPE='main' METAMASK_ENVIRONMENT='production' yarn build:android:pre-release:bundle
+                echo 'This is the current build type: $METAMASK_BUILD_TYPE'
+                if [ "$METAMASK_BUILD_TYPE" = "main" ]; then
+                    METAMASK_BUILD_TYPE='main' METAMASK_ENVIRONMENT='production' yarn build:android:pre-release:bundle
+                elif [ "$METAMASK_BUILD_TYPE" = "beta" ]; then
+                    METAMASK_BUILD_TYPE='beta' METAMASK_ENVIRONMENT='production' yarn build:android:pre-release:bundle:beta
+                elif [ "$METAMASK_BUILD_TYPE" = "flask" ]; then
+                    METAMASK_BUILD_TYPE='flask' METAMASK_ENVIRONMENT='production' yarn build:android:pre-release:bundle:beta
+                else
+                    echo "Error: Invalid build type specified: $METAMASK_BUILD_TYPE"
+                    exit 1
+                fi
           title: Build Android Pre-Release Bundle
           is_always_run: false
       - save-gradle-cache@1: {}
@@ -1243,6 +1253,132 @@ workflows:
       bitrise.io:
         stack: linux-docker-android-22.04
         machine_type_id: elite-xl
+
+  # # Template workflow for common iOS build steps
+  # _ios_build_template:
+  #   steps:
+  #     - set-xcode-build-number@1:
+  #         inputs:
+  #           - build_version: $VERSION_NAME
+  #           - build_short_version_string: $VERSION_NUMBER
+  #           - plist_path: $PROJECT_LOCATION_IOS/MetaMask/Info.plist
+  #     - certificate-and-profile-installer@1: {}
+  #     - restore-cocoapods-cache@1: {}
+  #     - script@1:
+  #         inputs:
+  #           - content: |-
+  #               #!/usr/bin/env bash
+  #               node -v
+  #               METAMASK_BUILD_TYPE='$METAMASK_BUILD_TYPE' METAMASK_ENVIRONMENT='production' yarn build:ios:pre-release
+  #         title: Build iOS $METAMASK_BUILD_TYPE Pre-Release
+  #     - save-cocoapods-cache@1: {}
+  #     - deploy-to-bitrise-io@2:
+  #         inputs:
+  #           - deploy_path: $IPA_PATH
+  #     - deploy-to-bitrise-io@2:
+  #         inputs:
+  #           - deploy_path: $DSYM_PATH
+
+  # Actual workflows that inherit from templates
+  build_android_release:
+    envs:
+      - METAMASK_BUILD_TYPE: "main"
+    after_run:
+      - _android_build_template
+
+  build_android_beta:
+    envs:
+      - METAMASK_BUILD_TYPE: "beta"
+    after_run:
+      - _android_build_template
+
+  # build_ios_release:
+  #   envs:
+  #     - METAMASK_BUILD_TYPE: "main"
+  #   before_run:
+  #     - code_setup
+  #     - _ios_build_template
+  #   after_run:
+  #     - notify_failure
+
+  # build_ios_beta:
+  #   envs:
+  #     - METAMASK_BUILD_TYPE: "beta"
+  #   before_run:
+  #     - code_setup
+  #     - _ios_build_template
+  #   after_run:
+  #     - notify_failure
+
+  
+  # build_android_release:
+  #   before_run:
+  #     - code_setup
+  #   after_run:
+  #     - notify_failure
+  #   steps:
+  #     - change-android-versioncode-and-versionname@1:
+  #         inputs:
+  #           - new_version_name: $VERSION_NAME
+  #           - new_version_code: $VERSION_NUMBER
+  #           - build_gradle_path: $PROJECT_LOCATION_ANDROID/app/build.gradle
+  #     - file-downloader@1:
+  #         inputs:
+  #           - source: $BITRISEIO_ANDROID_KEYSTORE_URL
+  #           - destination: android/keystores/release.keystore
+  #     - restore-gradle-cache@2: {}
+  #     - install-missing-android-tools@3:
+  #         inputs:
+  #           - ndk_version: $NDK_VERSION
+  #           - gradlew_path: $PROJECT_LOCATION/gradlew
+  #     - script@1:
+  #         inputs:
+  #           - content: |-
+  #               #!/usr/bin/env bash
+  #               node -v
+  #               METAMASK_BUILD_TYPE='main' METAMASK_ENVIRONMENT='production' yarn build:android:pre-release:bundle
+  #         title: Build Android Pre-Release Bundle
+  #         is_always_run: false
+  #     - save-gradle-cache@1: {}
+  #     - deploy-to-bitrise-io@2.2.3:
+  #         is_always_run: false
+  #         is_skippable: true
+  #         inputs:
+  #           - pipeline_intermediate_files: $PROJECT_LOCATION/app/build/outputs/apk/prod/release/app-prod-release.apk:BITRISE_PLAY_STORE_APK_PATH
+  #           - deploy_path: $PROJECT_LOCATION/app/build/outputs/apk/prod/release/app-prod-release.apk
+  #         title: Bitrise Deploy APK
+  #     - deploy-to-bitrise-io@2.2.3:
+  #         is_always_run: false
+  #         is_skippable: true
+  #         inputs:
+  #           - pipeline_intermediate_files: $PROJECT_LOCATION/app/build/outputs/apk/prod/release/sha512sums.txt:BITRISE_PLAY_STORE_SHA512SUMS_PATH
+  #           - deploy_path: $PROJECT_LOCATION/app/build/outputs/apk/prod/release/sha512sums.txt
+  #         title: Bitrise Deploy Checksum
+  #     - deploy-to-bitrise-io@2.2.3:
+  #         is_always_run: false
+  #         is_skippable: true
+  #         inputs:
+  #           - pipeline_intermediate_files: $PROJECT_LOCATION/app/build/outputs/mapping/prodRelease/mapping.txt:BITRISE_PLAY_STORE_MAPPING_PATH
+  #           - deploy_path: $PROJECT_LOCATION/app/build/outputs/mapping/prodRelease/mapping.txt
+  #         title: Bitrise ProGuard Map Files
+  #     - deploy-to-bitrise-io@2.2.3:
+  #         is_always_run: false
+  #         is_skippable: true
+  #         inputs:
+  #           - pipeline_intermediate_files: $PROJECT_LOCATION/app/build/outputs/bundle/prodRelease/app-prod-release.aab:BITRISE_PLAY_STORE_ABB_PATH
+  #           - deploy_path: $PROJECT_LOCATION/app/build/outputs/bundle/prodRelease/app-prod-release.aab
+  #         title: Bitrise Deploy AAB
+  #     - deploy-to-bitrise-io@2.2.3:
+  #         is_always_run: false
+  #         is_skippable: true
+  #         inputs:
+  #           - pipeline_intermediate_files: sourcemaps/android/index.js.map:BITRISE_PLAY_STORE_SOURCEMAP_PATH
+  #           - deploy_path: sourcemaps/android/index.js.map
+  #         title: Bitrise Deploy Sourcemaps
+  #   meta:
+  #     bitrise.io:
+  #       stack: linux-docker-android-22.04
+  #       machine_type_id: elite-xl
   build_android_release_and_upload_sourcemaps:
     envs:
       - SENTRY_DISABLE_AUTO_UPLOAD: 'false'
