Revert "chore:  Implement retry logic for downloading nvm in Bitrise"
This reverts commit 65354a0e608cc47947e7cbfe5e6adc7d0e339ded.

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -252,31 +252,52 @@ workflows:
           title: node, yarn, corepack installation
           inputs:
             - content: |-
-                   #!/usr/bin/env bash
-                    echo "Gems being installed with bundler gem"
-                    bundle install --gemfile=ios/Gemfile
-                    echo "Node $NODE_VERSION being installed"
+                #!/usr/bin/env bash
+                echo "Gems being installed with bundler gem"
+                bundle install --gemfile=ios/Gemfile
+                echo "Node $NODE_VERSION being installed"
 
-                    set -e
+                set -e
 
-                    # Add and enable NVM
-                    wget --tries=3 --waitretry=5 -O install-nvm.sh "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh"
-                    echo "${NVM_SHA256SUM} install-nvm.sh" > install-nvm.sh.SHA256SUM
-                    sha256sum -c install-nvm.sh.SHA256SUM
-                    chmod +x install-nvm.sh && ./install-nvm.sh && rm ./install-nvm.sh
-                    source "${HOME}/.nvm/nvm.sh"
-                    echo 'source "${HOME}/.nvm/nvm.sh"' | tee -a ${HOME}/.{bashrc,profile}
+                # Add and enable NVM
+                wget -O install-nvm.sh "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh"
+                echo "${NVM_SHA256SUM} install-nvm.sh" > install-nvm.sh.SHA256SUM
+                sha256sum -c install-nvm.sh.SHA256SUM
+                chmod +x install-nvm.sh && ./install-nvm.sh && rm ./install-nvm.sh
+                source "${HOME}/.nvm/nvm.sh"
+                echo 'source "${HOME}/.nvm/nvm.sh"' | tee -a ${HOME}/.{bashrc,profile}
 
-                    nvm install ${NODE_VERSION}
+                 # Retry logic for Node installation
+                MAX_ATTEMPTS=3
+                ATTEMPT=1
+                until [ $ATTEMPT -gt $MAX_ATTEMPTS ]
+                do
+                  echo "Attempt $ATTEMPT to install Node.js"
+                  nvm install ${NODE_VERSION}
+                  INSTALL_STATUS=$? # Capture the exit status of the nvm install command
+                  if [ $INSTALL_STATUS -eq 0 ]; then
+                      echo "Node.js installation successful!"
+                      break
+                  else
+                      echo "Node.js installation failed with exit code $INSTALL_STATUS"
+                      ATTEMPT=$((ATTEMPT+1))
+                      echo "Node.js installation failed, retrying in 5 seconds..."
+                      sleep 5
+                  fi
+                done
 
-                    envman add --key PATH --value $PATH
+                if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
+                  echo "Node.js installation failed after $MAX_ATTEMPTS attempts."
+                  exit 1
+                fi
+                envman add --key PATH --value $PATH
 
-                    node --version
+                node --version
 
-                    echo "Corepack being installed with npm"
-                    npm i -g "corepack@$COREPACK_VERSION"
-                    echo "Corepack enabling $YARN_VERSION"
-                    corepack enable
+                echo "Corepack being installed with npm"
+                npm i -g "corepack@$COREPACK_VERSION"
+                echo "Corepack enabling $YARN_VERSION"
+                corepack enable
   install_applesimutils:
     steps:
       - script@1:
