fix: flakey asdf node version
- remove asdf
- replace with bitrise-nvm-step

Co-authored-by: legobeat <legobeat@anonymous.com>

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -203,9 +203,33 @@ workflows:
                 echo "Gems being installed with bundler gem"
                 bundle install
                 echo "Node $NODE_VERSION being installed with asdf"
-                asdf list all nodejs
-                asdf install nodejs "$NODE_VERSION"
-                asdf global nodejs "$NODE_VERSION"
+
+                # Install NVM
+                PROFILE=$HOME/.profile
+                touch $PROFILE
+                curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | PROFILE=$PROFILE bash
+                source $PROFILE
+
+                if [ ! -z "${working_dir}" ] ; then
+                  echo "Switching to working directory: ${working_dir}"
+
+                  cd "${working_dir}"
+                  if [ $? -ne 0 ] ; then
+                    echo "Failed to switch to working directory: ${working_dir}"
+                  fi
+                fi
+
+                # Install latest node version by default
+                # if [[ -z "$node_version" && ! -e "./.nvmrc" ]]; then node_version="node"; fi
+
+                nvm install ${NODE_VERSION}
+
+                envman add --key PATH --value $PATH
+
+                # using set -e earlier caused issues, so at least check if the install succeeded at the end
+                set -e
+                node --version
+
                 echo "Corepack being installed with npm"
                 npm i -g "corepack@$COREPACK_VERSION"
                 echo "Corepack enabling $YARN_VERSION"
@@ -1363,6 +1387,9 @@ app:
     - opts:
         is_expand: false
       IOS_APP_LINK: ''
+    - opts:
+        is_expand: false
+      NVM_VERSION: 0.39.7
     - opts:
         is_expand: false
       NODE_VERSION: 20.12.2
