fix: lint error

diff --git a/.github/workflows/build-android-e2e.yml b/.github/workflows/build-android-e2e.yml
--- a/.github/workflows/build-android-e2e.yml
+++ b/.github/workflows/build-android-e2e.yml
@@ -155,7 +155,10 @@ jobs:
         run: |
           yarn setup:github-ci --no-build-ios --no-build-android
           yarn expo export --platform android
-          [ ! -f "dist/_expo/static/js/android/index.js" ] && exit 1 || true
+          if [ ! -f "dist/_expo/static/js/android/index.js" ]; then
+            echo "Bundle not found"
+            exit 1
+          fi
 
       - name: Repackage APK
         if: ${{ steps.build-decision.outputs.build_method == 'repack' }}
diff --git a/.github/workflows/build-ios-e2e.yml b/.github/workflows/build-ios-e2e.yml
--- a/.github/workflows/build-ios-e2e.yml
+++ b/.github/workflows/build-ios-e2e.yml
@@ -186,7 +186,10 @@ jobs:
         run: |
           yarn setup:github-ci --no-build-ios --no-build-android
           yarn expo export --platform ios
-          [ ! -f "dist/_expo/static/js/ios/index.js" ] && exit 1 || true
+          if [ ! -f "dist/_expo/static/js/ios/index.js" ]; then
+            echo "Bundle not found"
+            exit 1
+          fi
 
       - name: Repackage App
         if: ${{ steps.build-decision.outputs.build_method == 'repack' }}
