fix: rebase

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -328,7 +328,41 @@ jobs:
             echo "This job only runs for pull requests."
             exit 0
           fi
+          # Bypass step if skip-sonar-cloud label is found
+          LABEL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/labels" | \
+          jq -r '.[] | select(.name=="skip-sonar-cloud") | .name')
 
+          if [[ "$LABEL" == "skip-sonar-cloud" ]]; then
+            echo "skip-sonar-cloud label found. Skipping SonarCloud Quality Gate check."
+          else
+            sleep 30
+
+            PROJECT_KEY="metamask-mobile"
+            PR_NUMBER="${{ github.event.pull_request.number }}"
+            SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
+
+            if [ -z "$PR_NUMBER" ]; then
+              echo "No pull request number found. Failing the check."
+              exit 1
+            fi
+
+            RESPONSE=$(curl -s -u "$SONAR_TOKEN:" \
+              "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_NUMBER")
+            echo "SonarCloud API Response: $RESPONSE"
+
+            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
+
+            if [[ "$STATUS" == "ERROR" ]]; then
+              echo "Quality Gate failed."
+              exit 1
+            elif [[ "$STATUS" == "OK" ]]; then
+              echo "Quality Gate passed."
+            else
+              echo "Could not determine Quality Gate status."
+              exit 1
+            fi
+          fi
   smart-e2e-selection:
     name: 'Smart E2E Selection'
     runs-on: ubuntu-latest
