test: revert debug changes in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,227 +3,226 @@ on:
   push:
     branches: [main]
   pull_request:
-  # merge_group:
-  #   types: [checks_requested]
-  # schedule:
-  #   # Run the full suite "overnight," once every hour from 2:00am UTC until 6:00am UTC.
-  #   # This helps to identy the flaky and failed tests on main branch
-  #   - cron: '0 2-6 * * *'
+  merge_group:
+    types: [checks_requested]
+  schedule:
+    # Run the full suite "overnight," once every hour from 2:00am UTC until 6:00am UTC.
+    # This helps to identy the flaky and failed tests on main branch
+    - cron: '0 2-6 * * *'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
   cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/stable')) }}
 
 jobs:
-  # check-diff:
-  #   runs-on: macos-latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb #v1
-  #       with:
-  #         ruby-version: '3.1.6'
-  #       env:
-  #         BUNDLE_GEMFILE: ios/Gemfile
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci
-  #     - name: Require clean working directory
-  #       shell: bash
-  #       run: |
-  #         if ! git diff --exit-code; then
-  #           echo "Working tree dirty at end of job"
-  #           exit 1
-  #         else
-  #           echo "No changes detected"
-  #         fi
-  # dedupe:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci --node
-  #     - name: Deduplicate dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn deduplicate
-  #     - name: Print error if duplicates found
-  #       shell: bash
-  #       run: |
-  #         if ! git diff --exit-code; then
-  #           echo "Duplicate dependencies detected; run 'yarn deduplicate' to remove them"
-  #           exit 1
-  #         fi
-  # git-safe-dependencies:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci --node
-  #     - name: Run @lavamoat/git-safe-dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn git-safe-dependencies
-  # scripts:
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     matrix:
-  #       scripts:
-  #         - lint
-  #         - lint:tsc
-  #         - format:check:changed
-  #         - audit:ci
-  #         - test:depcheck
-  #         - test:tgz-check
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 2
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci --node
-  #     - run: yarn ${{ matrix['scripts'] }}
-  #     - name: Require clean working directory
-  #       shell: bash
-  #       run: |
-  #         if ! git diff --exit-code; then
-  #           echo "Working tree dirty at end of job"
-  #           exit 1
-  #         else
-  #           echo "No changes detected"
-  #         fi
-  # unit-tests:
-  #   runs-on: ubuntu-latest
-  #   strategy:
-  #     matrix:
-  #       shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci --node
-  #     # The "10" in this command is the total number of shards. It must be kept
-  #     # in sync with the length of matrix.shard
-  #     - run: yarn test:unit --shard=${{ matrix.shard }}/10 --forceExit --silent --coverageReporters=json
-  #       env:
-  #         NODE_OPTIONS: --max_old_space_size=20480
-  #     - name: Rename coverage report to include shard number
-  #       shell: bash
-  #       run: |
-  #         mv ./tests/coverage/coverage-final.json ./tests/coverage/coverage-${{ matrix.shard }}.json
-  #     - uses: actions/upload-artifact@v4
-  #       with:
-  #         name: coverage-${{ matrix.shard }}
-  #         path: ./tests/coverage/coverage-${{ matrix.shard }}.json
-  #         if-no-files-found: error
-  #     - name: Require clean working directory
-  #       shell: bash
-  #       run: |
-  #         if ! git diff --exit-code; then
-  #           echo "Working tree dirty at end of job"
-  #           exit 1
-  #         else
-  #           echo "No changes detected"
-  #         fi
-  # merge-unit-tests:
-  #   runs-on: ubuntu-latest
-  #   needs: unit-tests
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version-file: '.nvmrc'
-  #         cache: yarn
-  #     - name: Install Yarn dependencies with retry
-  #       uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
-  #       with:
-  #         timeout_minutes: 10
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: yarn install --immutable
-  #     - name: Clean state and following up dependencies installation
-  #       run: yarn setup:github-ci --node
-  #     - uses: actions/download-artifact@v4
-  #       with:
-  #         path: tests/coverage/
-  #     - name: Gather partial coverage reports into one directory
-  #       shell: bash
-  #       run: |
-  #         mv ./tests/coverage/coverage-*/* ./tests/coverage
-  #     - run: yarn test:merge-coverage
-  #     - run: yarn test:validate-coverage
-  #     - uses: actions/upload-artifact@v4
-  #       with:
-  #         name: coverage
-  #         path: ./tests/merged-coverage/lcov.info
-  #         if-no-files-found: error
-  #     - name: Require clean working directory
-  #       shell: bash
-  #       run: |
-  #         if ! git diff --exit-code; then
-  #           echo "Working tree dirty at end of job"
-  #           exit 1
-  #         else
-  #           echo "No changes detected"
-  #         fi
-
+  check-diff:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb #v1
+        with:
+          ruby-version: '3.1.6'
+        env:
+          BUNDLE_GEMFILE: ios/Gemfile
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci
+      - name: Require clean working directory
+        shell: bash
+        run: |
+          if ! git diff --exit-code; then
+            echo "Working tree dirty at end of job"
+            exit 1
+          else
+            echo "No changes detected"
+          fi
+  dedupe:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci --node
+      - name: Deduplicate dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn deduplicate
+      - name: Print error if duplicates found
+        shell: bash
+        run: |
+          if ! git diff --exit-code; then
+            echo "Duplicate dependencies detected; run 'yarn deduplicate' to remove them"
+            exit 1
+          fi
+  git-safe-dependencies:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci --node
+      - name: Run @lavamoat/git-safe-dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn git-safe-dependencies
+  scripts:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        scripts:
+          - lint
+          - lint:tsc
+          - format:check
+          - audit:ci
+          - test:depcheck
+          - test:tgz-check
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 2
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci --node
+      - run: yarn ${{ matrix['scripts'] }}
+      - name: Require clean working directory
+        shell: bash
+        run: |
+          if ! git diff --exit-code; then
+            echo "Working tree dirty at end of job"
+            exit 1
+          else
+            echo "No changes detected"
+          fi
+  unit-tests:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci --node
+      # The "10" in this command is the total number of shards. It must be kept
+      # in sync with the length of matrix.shard
+      - run: yarn test:unit --shard=${{ matrix.shard }}/10 --forceExit --silent --coverageReporters=json
+        env:
+          NODE_OPTIONS: --max_old_space_size=20480
+      - name: Rename coverage report to include shard number
+        shell: bash
+        run: |
+          mv ./tests/coverage/coverage-final.json ./tests/coverage/coverage-${{ matrix.shard }}.json
+      - uses: actions/upload-artifact@v4
+        with:
+          name: coverage-${{ matrix.shard }}
+          path: ./tests/coverage/coverage-${{ matrix.shard }}.json
+          if-no-files-found: error
+      - name: Require clean working directory
+        shell: bash
+        run: |
+          if ! git diff --exit-code; then
+            echo "Working tree dirty at end of job"
+            exit 1
+          else
+            echo "No changes detected"
+          fi
+  merge-unit-tests:
+    runs-on: ubuntu-latest
+    needs: unit-tests
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+          cache: yarn
+      - name: Install Yarn dependencies with retry
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: yarn install --immutable
+      - name: Clean state and following up dependencies installation
+        run: yarn setup:github-ci --node
+      - uses: actions/download-artifact@v4
+        with:
+          path: tests/coverage/
+      - name: Gather partial coverage reports into one directory
+        shell: bash
+        run: |
+          mv ./tests/coverage/coverage-*/* ./tests/coverage
+      - run: yarn test:merge-coverage
+      - run: yarn test:validate-coverage
+      - uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          path: ./tests/merged-coverage/lcov.info
+          if-no-files-found: error
+      - name: Require clean working directory
+        shell: bash
+        run: |
+          if ! git diff --exit-code; then
+            echo "Working tree dirty at end of job"
+            exit 1
+          else
+            echo "No changes detected"
+          fi
   integration-tests:
     runs-on: ubuntu-latest
     steps:
@@ -241,7 +240,7 @@ jobs:
           command: yarn install --immutable
       - name: Clean state and following up dependencies installation
         run: yarn setup:github-ci --node
-      - run: yarn test:integration --forceExit --silent
+      - run: yarn test:integration --coverage=false --forceExit --silent
         env:
           NODE_OPTIONS: --max_old_space_size=20480
       - name: Rename coverage report to include shard number
@@ -305,8 +304,30 @@ jobs:
             echo "No changes detected"
           fi
 
-  # needs_e2e_build:
-  #   uses: ./.github/workflows/needs-e2e-build.yml
+          # Revert git update-index --no-assume-unchanged for each entry
+          echo "Reverting assume unchanged for the following paths:"
+          for path in "${EXCLUDES[@]}"; do
+            echo "$path"
+            git update-index --no-assume-unchanged "$path"
+          done
+  sonar-cloud-quality-gate-status:
+    runs-on: ubuntu-latest
+    needs: sonar-cloud
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: SonarCloud Quality Gate Status
+        id: sonar-status
+        env:
+          REPO: ${{ github.repository }}
+          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Skip step if event is not a PR
+          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
+            echo "This job only runs for pull requests."
+            exit 0
+          fi
 
   smart-e2e-selection:
     name: 'Smart E2E Selection'
@@ -354,24 +375,19 @@ jobs:
       keystore_target: 'qa'
     secrets: inherit
 
-  # build-ios-apps:
-  #   name: 'Build iOS Apps'
-  #   if: ${{ github.event_name != 'merge_group' && needs.needs_e2e_build.outputs.ios_changed == 'true'}}
-  #   permissions:
-  #     contents: read
-  #     id-token: write
-  #   needs: [needs_e2e_build]
-  #   uses: ./.github/workflows/build-ios-e2e.yml
-  #   secrets: inherit
+          # Check E2E jobs only if they should have run
+          if [[ "${{ needs.needs_e2e_build.outputs.builds }}" == "true" ]]; then
+            if [[ "${{ needs.e2e-smoke-tests-android.result }}" == "failure" ]]; then
+              echo "Android E2E tests failed"
+              exit 1
+            fi
+            if [[ "${{ needs.e2e-smoke-tests-ios.result }}" == "failure" ]]; then
+              echo "iOS E2E tests failed"
+              exit 1
+            fi
+          fi
 
-  # ios-tests-ready:
-  #   name: 'iOS Tests Ready'
-  #   runs-on: ubuntu-latest
-  #   if: ${{ github.event_name != 'merge_group' && needs.needs_e2e_build.outputs.ios_changed == 'true'}}
-  #   needs: [needs_e2e_build, build-ios-apps]
-  #   steps:
-  #     - name: iOS build complete
-  #       run: echo "Dummy step to better visualize the Android and iOS E2E tests in Github workflow graph"
+          echo "All required jobs passed"
 
   # e2e-smoke-tests-ios:
   #   name: 'iOS E2E Smoke Tests'
