cfgs

diff --git a/.github/workflows/keystore-test-android-env.yml b/.github/workflows/keystore-test-android-env.yml
--- a/.github/workflows/keystore-test-android-env.yml
+++ b/.github/workflows/keystore-test-android-env.yml
@@ -7,7 +7,6 @@ permissions:
   contents: write
   id-token: write
 
-
 jobs:
   ios-e2e:
     runs-on: ubuntu-latest
@@ -17,7 +16,6 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v4
 
-
       - name: Setup Keystores for iOS E2E Tests
         uses: MetaMask/github-tools/.github/actions/configure-keystore@e2e-env-actions-keystore
         with:
@@ -26,8 +24,14 @@ jobs:
           platform: 'android'
           environment: 'qa'
 
+      - name: Check keystore file and contents
+        shell: bash
+        run: |
+          echo "📁 Checking keystore file at: $ANDROID_KEYSTORE_PATH"
+          ls -l "$ANDROID_KEYSTORE_PATH" || echo "❌ Keystore file not found"
 
-
-
-
-
+          echo "🔐 Listing keystore entries..."
+          keytool -list \
+            -keystore "$ANDROID_KEYSTORE_PATH" \
+            -storepass "$BITRISEIO_ANDROID_QA_KEYSTORE_PASSWORD" \
+            -v | grep "qa" || echo "⚠️ No aliases found or invalid password"
