experiment: workflows to check if bitrise comment was posted, PR is not docs

diff --git a/.github/workflows/run-bitrise-e2e-check.yml b/.github/workflows/run-bitrise-e2e-check.yml
--- a/.github/workflows/run-bitrise-e2e-check.yml
+++ b/.github/workflows/run-bitrise-e2e-check.yml
@@ -26,11 +26,52 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_NUMBER: ${{ github.event.number || github.event.issue.number }}
+  
+  is-documentation-pull-request:
+    name: Check if pull request is for documentation
+    runs-on: ubuntu-latest
+    outputs:
+      IS_DOCS_PR: ${{ steps.is-docs.outputs.IS_DOCS_PR }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check if docs PR
+        id: is-docs
+        run: |
+          if [[ "${{ startsWith(github.event.pull_request.title, 'docs:') }}" == "true" ]]; then
+            echo "IS_DOCS_PR=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "IS_DOCS_PR=false" >> "$GITHUB_OUTPUT"
+  
+  check-if-bitrise-ran:
+  name: Checking to see if Bitrise comment was posted
+  runs-on: ubuntu-latest
+  steps:
+    - uses: actions/checkout@v3
+
+    - name: Check if PR has Bitrise status commented
+      id: check_bitrise_comment
+      run: |
+        PR_COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments")
+
+        if echo "$PR_COMMENTS" | grep -q "Bitrise"; then
+          echo "Bitrise comment found."
+          echo "BITRISE_COMMENT_EXISTS=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "No Bitrise comment found."
+          echo "BITRISE_COMMENT_EXISTS=false" >> "$GITHUB_OUTPUT"
+          exit 1  # Fail the job if the comment does not exist
+        fi
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Output Bitrise Comment Status
+      run: echo "Bitrise comment exists: ${{ steps.check_bitrise_comment.outputs.BITRISE_COMMENT_EXISTS }}"
 
   run-bitrise-e2e-check:
-    needs: is-fork-pull-request
+    needs: [is-fork-pull-request,is-documentation-pull-request,check-if-bitrise-ran]
     runs-on: ubuntu-latest
-    if: ${{ needs.is-fork-pull-request.outputs.IS_FORK == 'false' }}
+    if: ${{ needs.is-fork-pull-request.outputs.IS_FORK == 'false' && needs.is-documentation-pull-request.outputs.IS_DOCS_PR == 'false' }}
     permissions:
       pull-requests: write
       contents: write
