fix formatting

diff --git a/.github/workflows/run-bitrise-e2e-check.yml b/.github/workflows/run-bitrise-e2e-check.yml
--- a/.github/workflows/run-bitrise-e2e-check.yml
+++ b/.github/workflows/run-bitrise-e2e-check.yml
@@ -1,15 +1,20 @@
 name: Run Bitrise E2E Check
-
-on:
+'on':
   issue_comment:
-    types: [edited, deleted]
+    types:
+      - edited
+      - deleted
   pull_request:
-    types: [opened, reopened, labeled, unlabeled, synchronize]
-
+    types:
+      - opened
+      - reopened
+      - labeled
+      - unlabeled
+      - synchronize
 env:
-  E2E_LABEL: 'Run Smoke E2E'
-  E2E_PIPELINE: 'pr_smoke_e2e_pipeline'
-  WORKFLOW_NAME: 'run-bitrise-e2e-check'
+  E2E_LABEL: Run Smoke E2E
+  E2E_PIPELINE: pr_smoke_e2e_pipeline
+  WORKFLOW_NAME: run-bitrise-e2e-check
 
 jobs:
   is-fork-pull-request:
@@ -22,11 +27,12 @@ jobs:
       - uses: actions/checkout@v3
       - name: Determine whether this PR is from a fork
         id: is-fork
-        run: echo "IS_FORK=$(gh pr view --json isCrossRepository --jq '.isCrossRepository' "${PR_NUMBER}" )" >> "$GITHUB_OUTPUT"
+        run: |
+          echo "IS_FORK=$(gh pr view --json isCrossRepository --jq '.isCrossRepository' "${PR_NUMBER}" )" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PR_NUMBER: ${{ github.event.number || github.event.issue.number }}
-  
+
   is-documentation-pull-request:
     name: Check if pull request is for documentation
     runs-on: ubuntu-latest
@@ -41,35 +47,35 @@ jobs:
             echo "IS_DOCS_PR=true" >> "$GITHUB_OUTPUT"
           else
             echo "IS_DOCS_PR=false" >> "$GITHUB_OUTPUT"
-  
-  check-if-bitrise-ran:
-  name: Checking to see if Bitrise comment was posted
-  runs-on: ubuntu-latest
-  steps:
-    - uses: actions/checkout@v3
+          fi
 
-    - name: Check if PR has Bitrise status commented
-      id: check_bitrise_comment
-      run: |
-        PR_COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+  check-if-bitrise-ran:
+    name: Checking to see if Bitrise comment was posted
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check if PR has Bitrise status commented
+        id: check_bitrise_comment
+        run: |
+          PR_COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments")
 
-        if echo "$PR_COMMENTS" | grep -q "Bitrise"; then
-          echo "Bitrise comment found."
-          echo "BITRISE_COMMENT_EXISTS=true" >> "$GITHUB_OUTPUT"
-        else
-          echo "No Bitrise comment found."
-          echo "BITRISE_COMMENT_EXISTS=false" >> "$GITHUB_OUTPUT"
-          exit 1  # Fail the job if the comment does not exist
-        fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Output Bitrise Comment Status
-      run: echo "Bitrise comment exists ${{ steps.check_bitrise_comment.outputs.BITRISE_COMMENT_EXISTS }}"
+          if echo "$PR_COMMENTS" | grep -q "Bitrise"; then
+            echo "Bitrise comment found."
+            echo "BITRISE_COMMENT_EXISTS=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "No Bitrise comment found."
+            echo "BITRISE_COMMENT_EXISTS=false" >> "$GITHUB_OUTPUT"
+            exit 1  # Fail the job if the comment does not exist
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   run-bitrise-e2e-check:
-    needs: [is-fork-pull-request,is-documentation-pull-request,check-if-bitrise-ran]
+    needs:
+      - is-fork-pull-request
+      - is-documentation-pull-request
+      - check-if-bitrise-ran
     runs-on: ubuntu-latest
     if: ${{ needs.is-fork-pull-request.outputs.IS_FORK == 'false' && needs.is-documentation-pull-request.outputs.IS_DOCS_PR == 'false' }}
     permissions:
@@ -83,18 +89,17 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version-file: '.nvmrc'
+          node-version-file: .nvmrc
 
       - name: Install dependencies
-        run: yarn --immutable
-        working-directory: '.github/scripts'
+        run: |
+           yarn --immutable
+        working-directory: .github/scripts
 
       - name: Check Bitrise E2E Status
         env:
           BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
           BITRISE_APP_ID: ${{ secrets.BITRISE_APP_ID }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        # The status check created under this workflow may be bucketed under another check suite in Github actions. This is a result of workflows with the same triggers.
-        # For example, the status check may show as `CLA Signature Bot / Bitrise E2E Status`. This is a bug on Github's UI. https://github.com/orgs/community/discussions/24616
         run: yarn run run-bitrise-e2e-check
-        working-directory: '.github/scripts'
+        working-directory: .github/scripts
